label: TF1 Keras Cifar10 Partial Host/Local

ignore:
    - 'report.*'
    - saved_models

output: saved_models

#docker:
#    binds:
#        - "/media/:/data"

config:
    lr: 0.8
    batch_size: 128
    epochs: 15
    train_samples: 60000
    test_samples: 10000

command: /usr/bin/python3 model.py
