image: python:3.7.0-alpine3.8
build:
- pwd && ls -al
- pip install -r requirements.txt

build_files:
- requirements.txt

env:
- PATH

parameters:
    lr: 50
    optimizer: sgd
    training:
        epochs: 200
        samples: 10

command: python model.py {{training.epochs}} {{training.samples}} {{notexisting}}
